import type { Motion } from './types'
import { squat, squatFront } from './families/squat'
import { forearmPlank, pikePushUp, pushUp, wallHandstand } from './families/pushup'
import { hinge, swing } from './families/hinge'
import { bulgarian, jumpLunge, lateralLunge, lunge, stepUp } from './families/lunge'
import { bearPlank, birdDog, bridge, catCow, childsPose, cobra, crunch, deadBug, hollowHold, proneRaise, russianTwist, sidePlank, superman, supineDb } from './families/floor'
import { bentRow, chairDip, invertedRow, lateralRaise, standingDb } from './families/upper'
import { burpee, jumpingJack, runInPlace, shadowBox, skaters } from './families/cardio'
import { armCircles, calfStretch, chestOpener, dogToCobra, figureFour, hamstringStretch, hipCircles, hipFlexorStretch, inchworm, legSwings, worldsGreatest } from './families/stretch'
import * as yoga from './families/yoga'

export interface DemoMotion {
  id: string
  name: string
  motion: Motion
}

/** Every motion family/variant, used by the Animation Lab and the contact-sheet QA. */
export const DEMO_MOTIONS: DemoMotion[] = [
  { id: 'squat', name: 'Bodyweight squat', motion: squat() },
  { id: 'box-squat', name: 'Box squat', motion: squat({ box: true, depth: 0.82 }) },
  { id: 'goblet', name: 'Goblet squat', motion: squat({ arms: 'goblet' }) },
  { id: 'front-squat', name: 'DB front squat', motion: squat({ arms: 'rack' }) },
  { id: 'thruster', name: 'DB thruster', motion: squat({ arms: 'press' }) },
  { id: 'squat-jump', name: 'Squat jump', motion: squat({ jump: true }) },
  { id: 'wall-sit', name: 'Wall sit', motion: squat({ wall: true, hold: 0.95 }) },
  { id: 'squat-front', name: 'Squat (front)', motion: squatFront() },
  { id: 'pushup', name: 'Push-up', motion: pushUp() },
  { id: 'pushup-knees', name: 'Knee push-up', motion: pushUp({ knees: true }) },
  { id: 'pushup-incline', name: 'Incline push-up', motion: pushUp({ surface: 'chair' }) },
  { id: 'pushup-wall', name: 'Wall push-up', motion: pushUp({ surface: 'wall' }) },
  { id: 'pushup-decline', name: 'Decline push-up', motion: pushUp({ feetOn: 'chair' }) },
  { id: 'pushup-sag', name: 'Push-up (hip sag)', motion: pushUp({ fault: 'hipSag' }) },
  { id: 'plank-taps', name: 'Shoulder taps', motion: pushUp({ mode: 'taps' }) },
  { id: 'climbers', name: 'Mountain climbers', motion: pushUp({ mode: 'climbers' }) },
  { id: 'renegade', name: 'Renegade row', motion: pushUp({ mode: 'renegade' }) },
  { id: 'forearm-plank', name: 'Forearm plank', motion: forearmPlank() },
  { id: 'pike', name: 'Pike push-up', motion: pikePushUp() },
  { id: 'pike-elev', name: 'Elevated pike', motion: pikePushUp({ elevated: true }) },
  { id: 'handstand', name: 'Wall handstand', motion: wallHandstand() },
  { id: 'rdl', name: 'DB Romanian deadlift', motion: hinge({ load: 'pair' }) },
  { id: 'good-morning', name: 'Good morning', motion: hinge({ load: 'none', hands: 'cross' }) },
  { id: 'sl-rdl', name: 'Single-leg RDL', motion: hinge({ load: 'pair', singleLeg: true }) },
  { id: 'swing', name: 'DB swing', motion: swing() },
  { id: 'rev-lunge', name: 'Reverse lunge', motion: lunge() },
  { id: 'fwd-lunge', name: 'Forward lunge', motion: lunge({ kind: 'forward' }) },
  { id: 'split-squat', name: 'Split squat', motion: lunge({ kind: 'split', arms: 'pair' }) },
  { id: 'bulgarian', name: 'Bulgarian split squat', motion: bulgarian() },
  { id: 'step-up', name: 'Step-up', motion: stepUp() },
  { id: 'jump-lunge', name: 'Jump lunge', motion: jumpLunge() },
  { id: 'lateral-lunge', name: 'Lateral lunge', motion: lateralLunge() },
  { id: 'cossack', name: 'Cossack squat', motion: lateralLunge({ kind: 'cossack' }) },
  { id: 'curtsy', name: 'Curtsy lunge', motion: lateralLunge({ kind: 'curtsy' }) },
  { id: 'dead-bug', name: 'Dead bug', motion: deadBug() },
  { id: 'crunch', name: 'Crunch', motion: crunch() },
  { id: 'rev-crunch', name: 'Reverse crunch', motion: crunch('reverse') },
  { id: 'bicycle', name: 'Bicycle crunch', motion: crunch('bicycle') },
  { id: 'leg-raise', name: 'Leg raise', motion: crunch('legRaise') },
  { id: 'vup', name: 'V-up', motion: crunch('vup') },
  { id: 'hollow', name: 'Hollow hold', motion: hollowHold() },
  { id: 'bridge', name: 'Glute bridge', motion: bridge() },
  { id: 'sl-bridge', name: 'Single-leg bridge', motion: bridge({ single: true }) },
  { id: 'hip-thrust', name: 'Hip thrust', motion: bridge({ thrust: true, loaded: true }) },
  { id: 'floor-press', name: 'DB floor press', motion: supineDb('press') },
  { id: 'pullover', name: 'DB pullover', motion: supineDb('pullover') },
  { id: 'skull', name: 'Skull crusher', motion: supineDb('skull') },
  { id: 'superman', name: 'Superman', motion: superman() },
  { id: 'cobra', name: 'Cobra', motion: cobra() },
  { id: 'bird-dog', name: 'Bird dog', motion: birdDog() },
  { id: 'cat-cow', name: 'Cat-cow', motion: catCow() },
  { id: 'child', name: "Child's pose", motion: childsPose() },
  { id: 'bear', name: 'Bear plank', motion: bearPlank() },
  { id: 'twist', name: 'Russian twist', motion: russianTwist({ db: true }) },
  { id: 'side-plank', name: 'Side plank', motion: sidePlank() },
  { id: 'side-plank-knee', name: 'Side plank (knees)', motion: sidePlank({ knees: true }) },
  { id: 'ytw', name: 'Prone Y-T-W', motion: proneRaise('ytw') },
  { id: 'snow-angel', name: 'Reverse snow angel', motion: proneRaise('snowAngel') },
  { id: 'w-pull', name: 'Prone W pull', motion: proneRaise('wPull') },
  { id: 'curl', name: 'DB curl', motion: standingDb('curl') },
  { id: 'hammer', name: 'Hammer curl', motion: standingDb('hammer') },
  { id: 'press', name: 'DB overhead press', motion: standingDb('press') },
  { id: 'arnold', name: 'Arnold press', motion: standingDb('arnold') },
  { id: 'triceps', name: 'Overhead triceps ext.', motion: standingDb('triceps') },
  { id: 'shrug', name: 'DB shrug', motion: standingDb('shrug') },
  { id: 'lat-raise', name: 'Lateral raise', motion: lateralRaise() },
  { id: 'bent-row', name: 'DB bent-over row', motion: bentRow() },
  { id: 'one-arm-row', name: 'One-arm DB row', motion: bentRow({ oneArm: true }) },
  { id: 'dip', name: 'Chair dip', motion: chairDip() },
  { id: 'inv-row', name: 'Table inverted row', motion: invertedRow() },
  { id: 'inv-row-bent', name: 'Inverted row (knees bent)', motion: invertedRow({ bentKnees: true }) },
  { id: 'jacks', name: 'Jumping jacks', motion: jumpingJack() },
  { id: 'step-jacks', name: 'Step jacks', motion: jumpingJack({ step: true }) },
  { id: 'high-knees', name: 'High knees', motion: runInPlace('highKnees') },
  { id: 'march', name: 'March in place', motion: runInPlace('march') },
  { id: 'butt-kicks', name: 'Butt kicks', motion: runInPlace('buttKicks') },
  { id: 'skaters', name: 'Skaters', motion: skaters() },
  { id: 'boxing', name: 'Shadow boxing', motion: shadowBox() },
  { id: 'burpee', name: 'Burpee', motion: burpee('full') },
  { id: 'squat-thrust', name: 'Squat thrust', motion: burpee('thrust') },
  { id: 'step-burpee', name: 'Step-back burpee', motion: burpee('stepBack') },
  { id: 'arm-circles', name: 'Arm circles', motion: armCircles() },
  { id: 'hip-circles', name: 'Hip circles', motion: hipCircles() },
  { id: 'leg-swings', name: 'Leg swings', motion: legSwings() },
  { id: 'hip-flexor', name: 'Hip-flexor stretch', motion: hipFlexorStretch() },
  { id: 'hamstring', name: 'Hamstring stretch', motion: hamstringStretch() },
  { id: 'calf', name: 'Calf stretch', motion: calfStretch() },
  { id: 'chest-open', name: 'Chest opener', motion: chestOpener() },
  { id: 'figure4', name: 'Figure-4 stretch', motion: figureFour() },
  { id: 'wgs', name: "World's greatest stretch", motion: worldsGreatest() },
  { id: 'inchworm', name: 'Inchworm', motion: inchworm() },
  { id: 'dog-cobra', name: 'Down dog ↔ cobra', motion: dogToCobra() },
  // ---- Yoga (Bloom) ----
  { id: 'y-mountain', name: 'Mountain breath', motion: yoga.mountainBreath() },
  { id: 'y-half-sun', name: 'Half sun salutation', motion: yoga.halfSunSalutation() },
  { id: 'y-sun-gentle', name: 'Sun salutation (gentle)', motion: yoga.sunSalutation({ gentle: true }) },
  { id: 'y-sun', name: 'Sun salutation', motion: yoga.sunSalutation() },
  { id: 'y-chair', name: 'Chair pose', motion: yoga.chairPose() },
  { id: 'y-warrior1', name: 'Warrior I', motion: yoga.warrior1() },
  { id: 'y-warrior2', name: 'Warrior II', motion: yoga.warrior2() },
  { id: 'y-triangle', name: 'Triangle', motion: yoga.triangle() },
  { id: 'y-goddess', name: 'Goddess', motion: yoga.goddess() },
  { id: 'y-tree-kick', name: 'Tree (kickstand)', motion: yoga.treePose('kickstand') },
  { id: 'y-tree-calf', name: 'Tree (calf)', motion: yoga.treePose('calf') },
  { id: 'y-tree-thigh', name: 'Tree (thigh)', motion: yoga.treePose('thigh') },
  { id: 'y-warrior3-chair', name: 'Warrior III (chair)', motion: yoga.warrior3({ chair: true }) },
  { id: 'y-warrior3', name: 'Warrior III', motion: yoga.warrior3() },
  { id: 'y-side-bend', name: 'Standing side bend', motion: yoga.standingSideBend() },
  { id: 'y-fold', name: 'Standing forward fold', motion: yoga.standingFold() },
  { id: 'y-low-lunge', name: 'Low lunge', motion: yoga.lowLunge() },
  { id: 'y-lizard', name: 'Lizard lunge', motion: yoga.lizardLunge() },
  { id: 'y-half-splits', name: 'Half splits', motion: yoga.halfSplits() },
  { id: 'y-pigeon', name: 'Pigeon', motion: yoga.pigeon() },
  { id: 'y-pigeon-fold', name: 'Sleeping pigeon', motion: yoga.pigeon({ fold: true }) },
  { id: 'y-down-dog', name: 'Downward dog', motion: yoga.downDog() },
  { id: 'y-puppy', name: 'Puppy pose', motion: yoga.puppyPose() },
  { id: 'y-sphinx', name: 'Sphinx', motion: yoga.sphinx() },
  { id: 'y-locust', name: 'Locust', motion: yoga.locust() },
  { id: 'y-bridge', name: 'Bridge (hold)', motion: yoga.bridgeHold() },
  { id: 'y-happy-baby', name: 'Happy baby', motion: yoga.happyBaby() },
  { id: 'y-knees-chest', name: 'Knees to chest', motion: yoga.kneesToChest() },
  { id: 'y-legs-wall', name: 'Legs up the wall', motion: yoga.legsUpWall() },
  { id: 'y-savasana', name: 'Savasana', motion: yoga.savasana() },
  { id: 'y-toe-taps', name: 'Toe taps', motion: yoga.toeTaps() },
  { id: 'y-twist', name: 'Supine twist', motion: yoga.supineTwist() },
  { id: 'y-recl-butterfly', name: 'Reclined butterfly', motion: yoga.reclinedButterfly() },
  { id: 'y-easy-seat', name: 'Easy seat', motion: yoga.easySeat() },
  { id: 'y-neck', name: 'Neck release', motion: yoga.neckRelease() },
  { id: 'y-seated-side', name: 'Seated side bend', motion: yoga.seatedSideBend() },
  { id: 'y-butterfly', name: 'Butterfly', motion: yoga.butterfly() },
  { id: 'y-seated-fold', name: 'Seated forward fold', motion: yoga.seatedForwardFold() },
  { id: 'y-boat', name: 'Boat', motion: yoga.boat() },
  { id: 'y-boat-easy', name: 'Boat (feet down)', motion: yoga.boat({ easy: true }) },
]
